In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score
from sklearn.metrics import recall_score, f1_score, roc_auc_score, classification_report
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB,GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score,classification_report,auc,roc_curve,roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
seed=42
import unicodedata
from nltk.corpus import stopwords
stop = stopwords.words('spanish')
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import word_tokenize as TK
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

# Para visualizar
import pyLDAvis
import pyLDAvis.gensim
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import FunctionTransformer


In [3]:
tw = pd.read_csv('tweets_clean4.2 - para prediccion.csv')

In [4]:
tw['sent'].value_counts(normalize=True)

1.0    0.714557
0.0    0.285443
Name: sent, dtype: float64

In [5]:
tw

Unnamed: 0                  timestamp                   id  \
0               0  2019-10-27 12:53:55+00:00  1162811195671416833   
1               1  2019-10-27 12:53:56+00:00            404900481   
2               2  2019-10-27 12:53:59+00:00  1165778412637736963   
3               3  2019-10-27 12:53:59+00:00            391643721   
4               4  2019-10-27 12:54:03+00:00  1153794949336444928   
...           ...                        ...                  ...   
11584       11584  2019-10-27 19:06:10+00:00           1552580563   
11585       11585  2019-10-27 19:06:10+00:00            239100413   
11586       11586  2019-10-27 19:06:11+00:00           1302834792   
11587       11587  2019-10-27 19:06:12+00:00           2728707039   
11588       11588  2019-10-27 19:06:12+00:00  1175418454850994176   

             username                                          text_orig  \
0          annyroshi_  #felizdomingo! hoy es un día especial y vale l...   
1           gonza_v12  todas las boletas de macri rotas. escuela 57 d...   
2             comunon  mas denuncias\nmas escuelas clausuradas\nmenos...   
3         marchaorgar  #eleccionesargentina\n\nmientras nos preparamo...   
4         xisdavidaii  que nuestros hermanos tengan sabiduría y hagan...   
...               ...                                                ...   
11584    aydaralfredo  ché @fantinofantino te acordas cuando le grita...   
11585   rafaelperafan  en el municipio de #topaipi en      #cundinama...   
11586        aleph52v  #cepo #volvimos primeras imágenes en el búnker...   
11587    laligrumelli  horas antes de que salgan los resultados ya ha...   
11588  nafisa14453347  https://t.co/lcjxyconoa\nthe grimeyboys tv sho...   

                                              text_modif  \
0      hoy es un dia especial y vale la pena correrme...   
1      todas las boletas de macri rotas escuela 57 de...   
2      mas denuncias\nmas escuelas clausuradas\nmenos...   
3      mientras nos preparamos para el festejo nos an...   
4      que nuestros hermanos tengan sabiduria y hagan...   
...                                                  ...   
11584  che te acordas cuando le gritabas apara turco ...   
11585  en el municipio de enpartidarios del candidato...   
11586  primeras imagenes en el bunker de macri despue...   
11587  horas antes de que salgan los resultados ya ha...   
11588               the grimeyboys tv show\namazing show   

                                                 text_en  lenght  \
0      Today is a special day and it is worth taking ...     252   
1      all the macri school 57 broken tickets of el p...     111   
2      more complaints more schools closed less kirch...     277   
3      As we prepare for the celebration, we encourag...     211   
4      that our brothers have wisdom and make the bes...     142   
...                                                  ...     ...   
11584  What do you remember when you yelled Turkish a...     234   
11585  in the municipality of enpartidarios of the ca...     250   
11586  first images in the macri bunker after announc...     157   
11587  hours before the results come out there was al...     225   
11588                the grimeyboys tv show amazing show     280   

                                           hashtags_orig  \
0             ['#felizdomingo!', '#eleccionesargentina']   
1                               ['#eleccionesargentina']   
2      ['#seamoslibreslodemassearregla', '#sisepuede'...   
3                 ['#eleccionesargentina', '#argentina']   
4                               ['#eleccionesargentina']   
...                                                  ...   
11584  ['#albertopresidente', '#periodismobasura', '#...   
11585   ['#topaipi', '#cundinamarca', '#elecciones2019']   
11586     ['#cepo', '#volvimos', '#eleccionesargentina']   
11587                        ['#eleccionesenpublicable']   
11588  ['#crackerswalidiwali', '#eleccionesargentina'...   

      

In [6]:
import nltk
#Importamos las StopWord para español
stopwords = nltk.corpus.stopwords.words('spanish')

#Agregamos algunas stopword mas que aportaban solo ruido
newStopWords = ['mas','bettina', 'romero', 'aos', 'tambien', 'chavistas', 'looken']
stopwords.extend(newStopWords)

In [231]:
#Realizamos el split
X_train, X_test, y_train, y_test = train_test_split(tw['text_modif'], tw['sent'],random_state=42, stratify=tw['sent'])

In [232]:
vect= TfidfVectorizer(stop_words=None,min_df=5,ngram_range=(1, 7))
X_train=vect.fit_transform(X_train)

In [233]:
X_train

<8691x11200 sparse matrix of type '<class 'numpy.float64'>'
	with 216836 stored elements in Compressed Sparse Row format>

In [209]:
pipe_master = Pipeline([
    ('vect', TfidfVectorizer()),
    ('model', model)

SyntaxError: unexpected EOF while parsing (<ipython-input-209-2d8a0cfaca31>, line 3)

In [210]:
y_train

3317     1.0
4554     1.0
6489     1.0
8683     0.0
2275     1.0
        ... 
9962     1.0
147      1.0
10338    1.0
3456     0.0
10380    1.0
Name: sent, Length: 8691, dtype: float64

In [149]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation


In [211]:

def batch_generator(X_data, y_data, batch_size):
    samples_per_epoch = X_data.shape[0]
    number_of_batches = samples_per_epoch/batch_size
    counter=0
    index = np.arange(np.shape(y_data)[0])
    while 1:
        index_batch = index[batch_size*counter:batch_size*(counter+1)]
        X_batch = X_data[index_batch,:].toarray()
        y_batch = y_data[y_data.index[index_batch]]
        counter += 1
        yield X_batch,y_batch
        if (counter > number_of_batches):
            counter=0

In [234]:
dim=X_train.shape[1]
dim

11200

In [235]:
%%time
dim=X_train.shape[1]
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_dim=dim)),
model.add(Dense(32, activation='sigmoid')),
model.add(Dense(16, activation='sigmoid')),
model.add(Dropout(0.5)),
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit_generator(generator=batch_generator(X_train, y_train, 32),
                    epochs=10,
                    steps_per_epoch=X_train.shape[0]/32)

Epoch 1/10
272/271 [==============================] - 4s 14ms/step - loss: 0.6641 - acc: 0.6435
Epoch 2/10
272/271 [==============================] - 3s 9ms/step - loss: 0.6157 - acc: 0.7087
Epoch 3/10
272/271 [==============================] - 3s 10ms/step - loss: 0.6076 - acc: 0.7136
Epoch 4/10
272/271 [==============================] - 3s 10ms/step - loss: 0.5958 - acc: 0.7146
Epoch 5/10
272/271 [==============================] - 3s 9ms/step - loss: 0.5307 - acc: 0.7378
Epoch 6/10
272/271 [==============================] - 3s 9ms/step - loss: 0.3604 - acc: 0.8529
Epoch 7/10
272/271 [==============================] - 3s 10ms/step - loss: 0.2643 - acc: 0.9024
Epoch 8/10
272/271 [==============================] - 3s 9ms/step - loss: 0.2023 - acc: 0.9300
Epoch 9/10
272/271 [==============================] - 3s 10ms/step - loss: 0.1625 - acc: 0.9513
Epoch 10/10
272/271 [==============================] - 3s 9ms/step - loss: 0.1314 - acc: 0.9630
Wall time: 27.9 s


In [236]:
pipe_master = Pipeline([
    ('vect', TfidfVectorizer())])

In [237]:
y_preds=model.predict(X_train)

In [238]:
y_preds

array([[0.9920299 ],
       [0.99622965],
       [0.9887533 ],
       ...,
       [0.99561465],
       [0.0158515 ],
       [0.9959096 ]], dtype=float32)

In [239]:
y_preds_int=y_preds.round(0)

In [240]:
y_preds_int

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [0.],
       [1.]], dtype=float32)

In [241]:
y_preds_int

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [0.],
       [1.]], dtype=float32)

In [242]:
print(classification_report(y_train, y_preds_int))

              precision    recall  f1-score   support

         0.0       0.96      0.97      0.97      2481
         1.0       0.99      0.98      0.99      6210

    accuracy                           0.98      8691
   macro avg       0.97      0.98      0.98      8691
weighted avg       0.98      0.98      0.98      8691



In [243]:
X_test=vect.transform(X_test)

In [244]:
y_preds_test=model.predict(X_test).round(0)


In [245]:
print(classification_report(y_test, y_preds_test))

              precision    recall  f1-score   support

         0.0       0.69      0.69      0.69       827
         1.0       0.88      0.87      0.87      2071

    accuracy                           0.82      2898
   macro avg       0.78      0.78      0.78      2898
weighted avg       0.82      0.82      0.82      2898



In [246]:
model.predict(vect.transform(['Celebramos la democracia una vez más! Se siente, se siente Alberto Presidente'])).round(0)

array([[0.]], dtype=float32)

In [247]:
model.predict(vect.transform(['No pudieron. Ni trayendo matones de La Matanza , ni tirando clavos miguelito, ni robando boletas. Simplemente Dolores les que dijo que NO!! '])).round(0)

array([[1.]], dtype=float32)

In [248]:
model.predict(vect.transform(['Iban a volver mejores, y terminaron anunciando que van a eliminar el decreto que declara a Hezbollah como organización terrorista. Se están pasando a los muertos de la AMIA por el orto y ustedes lo votaron, pelotudos.'])).round(0)

array([[0.]], dtype=float32)

In [249]:
model.predict(vect.transform(['Buen Domingo Para Todes! Yo estoy camino al colegio a Votar y después a trabajar! Le dejo el Pronóstico!'])).round(0)

array([[1.]], dtype=float32)

In [250]:
model.predict(vect.transform(['Por Néstor, por nuestra querida Patria. Para que vuelvan los días felices. VAMOS  Alberto, desde cada rincón estamos con vos.'])).round(0)

array([[1.]], dtype=float32)

In [251]:

model.predict(vect.transform(['que pobre el periodismo! ya ni siquiera me da bronca lo que dan es pena'])).round(0)

array([[0.]], dtype=float32)

In [252]:
confusion_matrix(y_test,y_preds_test)

array([[ 570,  257],
       [ 262, 1809]], dtype=int64)

In [253]:
print('AUC Train')
print(roc_auc_score(y_train,y_preds))
print('-------------------')
print('AUC Test')
print(roc_auc_score(y_test,y_preds_test))

AUC Train
0.9938501695007663
-------------------
AUC Test
0.7813646387581836
